app:
  messaging:
    input-topic: ${APP_MESSAGING_INPUT_TOPIC:stochastic-input}
  kafka:
    consumer:
      enabled: ${APP_KAFKA_CONSUMER_ENABLED:true}

server:
  port: ${SERVER_PORT:8082}

spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      database-platform: postgres

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:stochastic_labs_db}
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:root}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    producer:
      acks: all