server:
  port: ${SERVER_PORT:8082}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    template:
      retry:
        enabled: true
        initial-interval: 2000ms
        max-attempts: 3

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

  batch:
    job:
      enabled: ${SPRING_BATCH_JOB_ENABLED:true}
    jdbc:
      initialize-schema: always
      database-platform: postgres

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:stochastic_labs_db}
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:root}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    producer:
      acks: all

app:
  api:
    http-enabled: ${APP_API_HTTP_ENABLED:true}
  messaging:
    rabbit-exchange: ${APP_RABBIT_EXCHANGE:stochastic-exchange}
    rabbit-routing-key: ${APP_RABBIT_ROUTING_KEY:stochastic-routing-key-input}
  kafka:
    input-topic: ${APP_KAFKA_INPUT_TOPIC:stochastic-input}
    consumer:
      enabled: ${APP_KAFKA_CONSUMER_ENABLED:true}